name: armory_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  firebase_crashlytics: ^5.0.7
  firebase_analytics: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: "^0.13.1"

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ios.png"
  remove_alpha_ios: true
  
  adaptive_icon_background: "assets/icon/ic_launcher_adaptive_back.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_adaptive_fore.png"


flutter:
  uses-material-design: true

  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf

  assets:
    - assets/icon/
    - assets/Akimbo_202602130023.json
    - assets/Ammo_Mods_202602141947.json
    - assets/CAD_202602140253.json
    - assets/Cold_War_Akimbo_202602130024.json
    - assets/Cold_War_Single_202602130024.json
    - assets/Endgame_BO7_202602130023.json
    - assets/Field_Upgrades_202602141947.json
    - assets/META_202602160120.json
    - assets/Multiplayer_BO7_202602130017.json
    - assets/Multiplayer_Cold_War_202602130020.json
    - assets/Multiplayer_MW19_202602130020.json
    - assets/Multiplayer_MW3_BO6_202602130020.json
    - assets/REBIRTH_202602130024.json
    - assets/Single_202602130024.json
    - assets/Special_202602130024.json
    - assets/Warzone_BO6_202602130021.json
    - assets/Warzone_BO7_202602130021.json
    - assets/Warzone_MW3_MW2_202602130021.json
    - assets/Zombies_BO7_202602130022.json
    - assets/Zombies_Cold_War_202602130022.json
    - assets/Zombies_MW3_BO6_202602130022.json
    - assets/Weapon_Names_202602160630.json
    - assets/Perks_202602141947.json
    - assets/Premium_Users_202602131455.json
    - assets/Premium_Stats_202602131455.json
    - assets/images/arm (1).jpg

flutter_native_splash:
  color: "#000000"
  image: assets/icon/ios.png
  android_12:
    image: assets/icon/ios.png
    color: "#000000"