name: armory_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  firebase_crashlytics: ^5.0.7
  firebase_analytics: ^12.1.2
  firebase_core: ^4.4.0
  cached_network_image: ^3.3.1
  flutter_colorpicker: ^1.1.0
  animations: ^2.0.11
  in_app_purchase: ^3.2.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ios.png"
  remove_alpha_ios: true
  
  adaptive_icon_background: "assets/icon/ic_launcher_adaptive_back.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_adaptive_fore.png"


flutter:
  uses-material-design: true

  fonts:
  
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf

    - family: Stock
      fonts:
        - asset: assets/fonts/DaysOne-Regular.ttf

    - family: Silkscreen
      fonts:
        - asset: assets/fonts/Silkscreen-Regular.ttf

    - family: Black Ops One
      fonts:
        - asset: assets/fonts/BlackOpsOne-Regular.ttf
        
    - family: Braah One
      fonts:
        - asset: assets/fonts/BraahOne-Regular.ttf

    - family: Fugaz One
      fonts:
        - asset: assets/fonts/FugazOne-Regular.ttf
    
    - family: Germania One
      fonts:
        - asset: assets/fonts/GermaniaOne-Regular.ttf

    - family: Kaushan Script
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf

    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf

    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf

    - family: Quantico
      fonts:
        - asset: assets/fonts/Quantico-Regular.ttf

    - family: Racing Sans
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf


    - family: Vast Shadow
      fonts:
        - asset: assets/fonts/VastShadow-Regular.ttf

  assets:
    - assets/icon/
    - assets/Akimbo_202603022137.json
    - assets/Ammo_Mods_202602141947.json
    - assets/CAD_202602140253.json
    - assets/Cold_War_Akimbo_202602130024.json
    - assets/Cold_War_Single_202602130024.json
    - assets/Endgame_BO7_202602130023.json
    - assets/Field_Upgrades_202602141947.json
    - assets/META_202602160120.json
    - assets/Multiplayer_BO7_202603041754.json
    - assets/Multiplayer_Cold_War_202603041703.json
    - assets/Multiplayer_MW19_202602130020.json
    - assets/Multiplayer_MW3_BO6_202602130020.json
    - assets/Ranked_202602202346.json
    - assets/REBIRTH_202602130024.json
    - assets/Single_202602130024.json
    - assets/Special_202602130024.json
    - assets/Warzone_BO6_202602130021.json
    - assets/Warzone_BO7_202602130021.json
    - assets/Warzone_MW3_MW2_202602130021.json
    - assets/Zombies_BO7_202602130022.json
    - assets/Zombies_Cold_War_202602130022.json
    - assets/Zombies_MW3_BO6_202602130022.json
    - assets/Weapon_Names_202602160630.json
    - assets/Perks_202602141947.json
    - assets/Premium_Users_202602131455.json
    - assets/Premium_Stats_202602131455.json
    - assets/images/arm (1).jpg
    - assets/MinMax_202603052106.json

flutter_native_splash:
  color: "#000000"
  image: assets/icon/ios.png
  android_12:
    image: assets/icon/ios.png
    color: "#000000"