// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzorg80cmQvsouD8UzkHjyezyBoYrNqWU',
    appId: '1:719501207701:web:dbcc54abc2188841bbd39c',
    messagingSenderId: '719501207701',
    projectId: 'armory-app-e8c90',
    authDomain: 'armory-app-e8c90.firebaseapp.com',
    storageBucket: 'armory-app-e8c90.firebasestorage.app',
    measurementId: 'G-SB6HD102D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnazKuOu68KRsIGJqW1N0WSg5wik7wOzQ',
    appId: '1:719501207701:android:502e1de1886410dfbbd39c',
    messagingSenderId: '719501207701',
    projectId: 'armory-app-e8c90',
    storageBucket: 'armory-app-e8c90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMo93mPm_ftFp7HXE48sc6JQbm40lN-Bk',
    appId: '1:719501207701:ios:117840d838bbbdc8bbd39c',
    messagingSenderId: '719501207701',
    projectId: 'armory-app-e8c90',
    storageBucket: 'armory-app-e8c90.firebasestorage.app',
    iosBundleId: 'com.example.armoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMo93mPm_ftFp7HXE48sc6JQbm40lN-Bk',
    appId: '1:719501207701:ios:117840d838bbbdc8bbd39c',
    messagingSenderId: '719501207701',
    projectId: 'armory-app-e8c90',
    storageBucket: 'armory-app-e8c90.firebasestorage.app',
    iosBundleId: 'com.example.armoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzorg80cmQvsouD8UzkHjyezyBoYrNqWU',
    appId: '1:719501207701:web:e35cc7233556fd94bbd39c',
    messagingSenderId: '719501207701',
    projectId: 'armory-app-e8c90',
    authDomain: 'armory-app-e8c90.firebaseapp.com',
    storageBucket: 'armory-app-e8c90.firebasestorage.app',
    measurementId: 'G-95D5EJYHNP',
  );
}
